## server post config
server:
  port: 80
## spring config
spring:
  banner:
    location: banner
  redis:
    host: 47.113.225.98
    password: '!tufirewall'
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ## mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.225.98:3306/turingoss?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '!Tufirewall123..'
  ## jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
## log4f config
logging:
  level:
    web: debug
## 存储路径映射
pathMap:
  source: F:\files\
## 临时文件格式
tmpFilePattern: '%stmp\%s.%d.chunk'
downloadAddr: http://localhost
## mbp
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
    banner: false
