## server post config
server:
  port: 80
## spring config
spring:
  banner:
    location: banner
  redis:
    host: 127.0.0.1
    password: 82995363epc
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  ## mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/turingoss?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 82995363epc
  ## jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
## log4f config
logging:
  level:
    web: debug
## 存储路径映射
pathMap:
  source: E:\files\
## 临时文件格式
tmpFilePattern: '%stmp\%s.%d.chunk'
downloadAddr: http://localhost
## mbp
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
    banner: false
##sa-token
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 2592000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  #从请求头获取token
  isReadHeader: true
  #禁用cookie
  isReadCookie: false
  # 是否输出操作日志
  is-log: true
  #自动续签
  autoRenew: true
  jwt-secret-key: asdibwaibiqwubfqofibbgoiqwnf