## server post config
server:
  port: 80

## spring config
spring:
  banner:
    location: banner
  redis:
    host: localhost
    password: root
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
## global id config
Snowflake:
  workerId: 1
  datacenterId: 1
## log4f config
logging:
  level:
    web: debug

## 存储路径映射
pathReflect:
  source:
    - D:\test\source
    - D:\test\source2
  target:
    - D:\test\target
    - D:\test\target2
